import QtQuick

ListModel {
    ListElement { name: "BTC" }
    ListElement { name: "ETH" }
    ListElement { name: "SOL" }
    ListElement { name: "USDT" }
    ListElement { name: "USDC" }
    ListElement { name: "AAVE" }
    ListElement { name: "ADA" }
    ListElement { name: "ALGO" }
    ListElement { name: "APT" }
    ListElement { name: "ARB" }
    ListElement { name: "ATOM" }
    ListElement { name: "AVAX" }
    ListElement { name: "BCH" }
    ListElement { name: "BNB" }
    ListElement { name: "BONK" }
    ListElement { name: "CAKE" }
    ListElement { name: "CHZ" }
    ListElement { name: "CRV" }
    ListElement { name: "DAI" }
    ListElement { name: "DEXE" }
    ListElement { name: "DOGE" }
    ListElement { name: "DOT" }
    ListElement { name: "DYDX" }
    ListElement { name: "ENA" }
    ListElement { name: "ENS" }
    ListElement { name: "EOS" }
    ListElement { name: "ETC" }
    ListElement { name: "FET" }
    ListElement { name: "FIL" }
    ListElement { name: "FLOKI" }
    ListElement { name: "FORM" }
    ListElement { name: "GALA" }
    ListElement { name: "HBAR" }
    ListElement { name: "ICP" }
    ListElement { name: "IMX" }
    ListElement { name: "INJ" }
    ListElement { name: "JTO" }
    ListElement { name: "JUP" }
    ListElement { name: "LDO" }
    ListElement { name: "LINK" }
    ListElement { name: "LTC" }
    ListElement { name: "MANA" }
    ListElement { name: "MKR" }
    ListElement { name: "NEAR" }
    ListElement { name: "ONDO" }
    ListElement { name: "OP" }
    ListElement { name: "PAXG" }
    ListElement { name: "PENDLE" }
    ListElement { name: "PEPE" }
    ListElement { name: "POL" }
    ListElement { name: "PYTH" }
    ListElement { name: "QNT" }
    ListElement { name: "RAY" }
    ListElement { name: "RENDER" }
    ListElement { name: "RONIN" }
    ListElement { name: "RUNE" }
    ListElement { name: "S" }
    ListElement { name: "SAND" }
    ListElement { name: "SEI" }
    ListElement { name: "SHIB" }
    ListElement { name: "STX" }
    ListElement { name: "SUI" }
    ListElement { name: "TAO" }
    ListElement { name: "TIA" }
    ListElement { name: "TON" }
    ListElement { name: "TRUMP" }
    ListElement { name: "TRX" }
    ListElement { name: "UNI" }
    ListElement { name: "USDS" }
    ListElement { name: "VET" }
    ListElement { name: "WBTC" }
    ListElement { name: "WLD" }
    ListElement { name: "XLM" }
    ListElement { name: "XMR" }
    ListElement { name: "XRP" }
}
